book:
    t:                "hols"
    title:            "Memoria Técnica del Proyecto"
    author:           "Luis Andreu Puchol"
    edition:          "Primera Edición"
    language:         es
    publication_date: 15-05-2012

    university:       "Universitat Jaume I"
    subject:          "II31 - Sistemas Informáticos"
    degree:           "Ingeniería Informática"
    course:           "2011-2012"
    project:          "Desarrollo de una herramienta web para el sistema de evaluación de la asignatura Prácticas en empresa y proyecto fin de grado del nuevo Grado en Ingeniería Informática"
    tutor:            "Ángeles López y Maria José Aramburu"   

    generator: { name: easybook, version: 4.4 }

    contents:
        # available content types: acknowledgement, afterword, appendix, author,
        # chapter, conclusion, cover, dedication, edition, epilogue, foreword,
        # glossary, introduction, license, lof (list of figures), lot (list of
        # tables), part, preface, prologue, title, toc (table of contents)
        #- { element: cover }
        - { element: title }
        - { element: toc   }
        #- { element: part, number: 1, title: "Introducción muy interesante" }
        - { element: chapter, number: 1, content: 1.introduccion.md }
        - { element: chapter, number: 2, content: 2.descripcion.md }
        - { element: chapter, number: 3, content: 3.planificacion.md }
        - { element: chapter, number: 4, content: 4.analisis.md }
        - { element: chapter, number: 5, content: 5.disenyo.md }
        - { element: chapter, number: 6, content: 6.implementacion.md }
        - { element: chapter, number: 7, content: 7.conclusiones.md }

    editions:
        ebook:
            format:         epub
            highlight_code: false
            include_styles: true
            labels:         ['appendix', 'chapter']  # labels also available for: "figure", "table"
            theme:          clean
            toc:
                deep:       2
                elements:   ["appendix", "chapter", "part"]

        print:
            format:         pdf
            highlight_code: true
            include_styles: true
            isbn:           ~
            labels:         ["appendix", "chapter"]  # labels also available for: "figure", "table"
            margin:
                top:        25mm
                bottom:     25mm
                inner:      30mm
                outter:     20mm
            page_size:      A4
            theme:          clean
            toc:
                deep:       2
                elements:   ["appendix", "chapter", "part"]
            two_sided:      true

        web:
            format:         html
            highlight_code: true
            include_styles: true
            labels:         ["appendix", "chapter"]  # labels also available for: "figure", "table"
            theme:          clean
            toc:
                deep:       2
                elements:   ["appendix", "chapter"]

        website:
            extends:        web
            format:         html_chunked
